Add more curl test code
Change-Id: I2634e63b62f5352a6e41fae10a2d7dbf23dcc341

diff --git a/.github/workflows/read-replica-test.yml b/.github/workflows/read-replica-test.yml
--- a/.github/workflows/read-replica-test.yml
+++ b/.github/workflows/read-replica-test.yml
@@ -24,8 +24,11 @@ jobs:
           # Self-healing check: Wait for Master UI to return 200 OK
           echo "waiting 15 seconds"
           sleep 15
-          echo "running 'curl http://hbase-docker:16010'"
+          echo "running 'curl --head  http://localhost:16010'"
           curl --head  http://localhost:16010
+          echo "Running: curl --output /dev/null --silent --head --fail http://localhost:16010"
+          curl --output /dev/null --silent --head --fail http://localhost:16010
+          echo "return code: $?"
           # until $(curl --output /dev/null --silent --head --fail http://hbase-docker:16010); do
           #   printf '.'
           #   sleep 5
