Go back to 'until' loop
Change-Id: I9e98b70d835ff669ab90841d042d220c454699e8

diff --git a/.github/workflows/read-replica-test.yml b/.github/workflows/read-replica-test.yml
--- a/.github/workflows/read-replica-test.yml
+++ b/.github/workflows/read-replica-test.yml
@@ -22,18 +22,18 @@ jobs:
           docker compose -f dev-support/integration-test/read-replica/docker-compose.test.yml up -d
           echo "Waiting for HBase clusters to initialize..."
           # Self-healing check: Wait for Master UI to return 200 OK
-          echo "waiting 15 seconds"
-          sleep 15
-          echo "running 'curl --head  http://localhost:16010'"
-          curl --head  http://localhost:16010
-          echo "Running: curl --output /dev/null --silent --head --fail http://localhost:16010"
-          curl --output /dev/null --silent --head --fail http://localhost:16010
-          echo "return code: $?"
-          # until $(curl --output /dev/null --silent --head --fail http://hbase-docker:16010); do
-          #   printf '.'
-          #   sleep 5
-          # done
-          # echo "Clusters are up!"
+          # echo "waiting 15 seconds"
+          # sleep 15
+          # echo "running 'curl --head  http://localhost:16010'"
+          # curl --head  http://localhost:16010
+          # echo "Running: curl --output /dev/null --silent --head --fail http://localhost:16010"
+          # curl --output /dev/null --silent --head --fail http://localhost:16010
+          # echo "return code: $?"
+          until $(curl --output /dev/null --silent --head --fail http://localhost:16010); do
+            echo -n "."
+            sleep 5
+          done
+          echo "Clusters are up!"
 
       - name: Check container status (optional)
         run: docker compose -f dev-support/integration-test/read-replica/docker-compose.test.yml ps
